window.onload = function () {
    settingUse();
    loadTheme();
    mainUse();
    dlUse();
    weatherUse();
    hideUse();
    hsFeatureUse();
    hsLinkUse();
    useLinkChange();
    calUse();
    getTime();
    one();
    oneUse();
    changeStyle();
    infoUse();
    historyUse();
    searchUse();
    searchChangeUse();
    searchOnload();
}