print('▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇')
print('▇▇▇▇▇▇hello world！▇▇▇▇▇▇')
print('▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇')
print('')
print('QQ: 1848367623')
print('Twitter: @Tony_Lu110')
print('github: https://github.com/tonylu110')
print('')
print('This project link is https://github.com/tonylu110/browserNewTabPage')